AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java Lambda with Firebase Authentication via Lambda Function URL and CloudFront

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Deployment environment (test or prod)

  FirebaseProject:
    Type: String
    Description: Firebase project ID for authentication

  ApiDomainName:
    Type: String
    Description: Custom domain for this API (for example, api-test.kitree.co.in or api.kitree.co.in)

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for ApiDomainName (must be in us-east-1 for CloudFront)


Globals:
  Function:
    Timeout: 300  # 5 minutes - allows time for audio download + Gemini API processing
    MemorySize: 1024  # Increased for audio file processing
    EphemeralStorage:
      Size: 1024  # 1GB temp storage for audio files
    LoggingConfig:
      LogFormat: JSON
      LogGroup: !Sub "/aws/lambda/kitree-lambda-${Environment}"
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN

Resources:
  # Lambda Function
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: in.co.kitree.Handler::handleRequest
      Runtime: java21
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: "https://dc337a8e397dd75f982b60a24018dd22@o1209671.ingest.us.sentry.io/4510843972354048"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:kitree-python-scripts-${Environment}"
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:kitree-astrology-api-${Environment}"
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:kitree-lambda-${Environment}"
      AutoPublishAlias: !Ref Environment
      DeploymentPreference:
        Type: !If [ IsProd, AllAtOnce, Canary10Percent5Minutes ]
      # New: Lambda Function URL (public, no IAM auth)
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"

  # CloudFront distribution in front of the Lambda Function URL
  ApiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CloudFront for kitree-lambda-${Environment}"
        Aliases:
          - !Ref ApiDomainName
        DefaultRootObject: ""
        DefaultCacheBehavior:
          TargetOriginId: lambda-origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled (auth header forwarded, no cross-user cache risk)
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # Managed-AllViewerExceptHostHeader
        Origins:
          - Id: lambda-origin
            # Extract the domain part from the Lambda Function URL
            DomainName: !Select [2, !Split ["/", !GetAtt JavaFunctionUrl.FunctionUrl]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/kitree-lambda-${Environment}"
      RetentionInDays: !If [ IsProd, 7, 1 ]

  # EventBridge Rule for auto-terminating stale on-demand consultations
  AutoTerminateConsultationsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "auto-terminate-consultations-${Environment}"
      Description: "Auto-terminate on-demand consultations that exceed max_allowed_duration"
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Id: JavaLambdaTarget
          Arn: !GetAtt JavaFunction.Arn
          Input: '{"source":"aws.events","detailType":"auto_terminate_consultations"}'

  # Permission for EventBridge to invoke Lambda
  AutoTerminateConsultationsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref JavaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AutoTerminateConsultationsRule.Arn

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]

Outputs:
  ApiEndpoint:
    Description: Lambda Function URL endpoint
    Value: !GetAtt JavaFunctionUrl.FunctionUrl

  ApiCustomDomainUrl:
    Description: Custom domain URL for this API via CloudFront
    Value: !Sub "https://${ApiDomainName}"

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt ApiDistribution.DomainName
