AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java Lambda with Firebase Authentication via API Gateway

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Deployment environment (test or prod)

  FirebaseProject:
    Type: String
    Description: Firebase project ID for authentication

  ApiDomainName:
    Type: String
    Default: ""
    Description: >
      Optional custom domain for this API (for example,
      api-test.kitree.co.in or api.kitree.co.in).

  CertificateArn:
    Type: String
    Default: ""
    Description: >
      ACM certificate ARN for ApiDomainName (must be in the same region as the API).

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    LoggingConfig:
      LogFormat: JSON
      LogGroup: !Sub "/aws/lambda/java-lambda-${Environment}"
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Environment
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
      Domain: !If
        - HasCustomDomain
        - DomainName: !Ref ApiDomainName
          CertificateArn: !Ref CertificateArn
          EndpointConfiguration: REGIONAL
        - !Ref "AWS::NoValue"

  # Lambda Function
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: in.co.kitree.Handler::handleRequest
      Runtime: java21
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:certgen"
      AutoPublishAlias: !Ref Environment
      DeploymentPreference:
        Type: !If [ IsProd, AllAtOnce, Canary10Percent5Minutes ]
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /api
            Method: ANY
            ApiId: !Ref ApiGateway

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/java-lambda-${Environment}"
      RetentionInDays: !If [ IsProd, 7, 1 ]

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]

  HasCustomDomain: !And
    - !Not [ !Equals [ !Ref ApiDomainName, "" ] ]
    - !Not [ !Equals [ !Ref CertificateArn, "" ] ]

Outputs:
  ApiEndpoint:
    Description: API Gateway default execute-api endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"

  ApiCustomDomainUrl:
    Condition: HasCustomDomain
    Description: Custom domain URL for this API
    Value: !Sub "https://${ApiDomainName}"
